export interface Player {
  name: string;
  number: number | null;
}

// Uniform numbers are the ones worn specifically during each player's Brewers
// tenure (sourced from Baseball-Reference / MLB.com / Baseball Almanac). Some
// numbers repeat across entries by design — the Brewers have recycled jersey
// numbers across different eras (e.g. both Jackson Chourio and Rowdy Tellez
// wore #11), which is historically accurate, not a data bug.
export const PLAYERS: Player[] = [
  { name: "Christian Yelich", number: 22 },
  { name: "William Contreras", number: 24 },
  { name: "Jackson Chourio", number: 11 },
  { name: "Brice Turang", number: 2 },
  { name: "Sal Frelick", number: 10 },
  { name: "Garrett Mitchell", number: 5 },
  { name: "Joey Ortiz", number: 3 },
  { name: "Andrew Vaughn", number: 28 },
  { name: "Jake Bauers", number: 9 },
  { name: "David Hamilton", number: 6 },
  { name: "Gary Sanchez", number: 99 },
  { name: "Jacob Misiorowski", number: 32 },
  { name: "Kyle Harrison", number: 52 },
  { name: "Chad Patrick", number: 39 },
  { name: "Trevor Megill", number: 29 },
  { name: "Abner Uribe", number: 45 },
  { name: "DL Hall", number: 37 },
  { name: "Aaron Ashby", number: 26 },
  { name: "Brandon Woodruff", number: 53 },
  { name: "Quinn Priester", number: 46 },

  { name: "Devin Williams", number: 38 },
  { name: "Willy Adames", number: 27 },
  { name: "Corbin Burnes", number: 39 },
  { name: "Josh Hader", number: 71 },
  { name: "Rhys Hoskins", number: 12 },
  { name: "Caleb Durbin", number: 21 },
  { name: "Freddy Peralta", number: 51 },
  { name: "Luis Rengifo", number: 13 },
  { name: "Rowdy Tellez", number: 11 },
  { name: "Robin Yount", number: 19 },
  { name: "Paul Molitor", number: 4 },
  { name: "Prince Fielder", number: 28 },
  { name: "Carlos Gomez", number: 27 },
  { name: "Yovani Gallardo", number: 49 },
  { name: "Scooter Gennett", number: 2 },
  { name: "Kolten Wong", number: 16 },
  { name: "Jonathan Lucroy", number: 20 },
  { name: "Jean Segura", number: 9 },
  { name: "CC Sabathia", number: 52 },
  { name: "Bill Hall", number: 2 },
  { name: "Corey Hart", number: 1 },
  { name: "Geoff Jenkins", number: 5 },
  { name: "Ben Sheets", number: 15 },
  { name: "Zack Greinke", number: 13 },
  { name: "Rollie Fingers", number: 34 },
  { name: "Hank Aaron", number: 44 },
  { name: "Lyle Overbay", number: 11 },
  { name: "Cecil Cooper", number: 15 },
  { name: "Ben Oglivie", number: 24 },
  { name: "Nyjer Morgan", number: 2 },
  { name: "John Axford", number: 59 },
  { name: "Rickie Weeks", number: 23 },
  { name: "JJ Hardy", number: 7 },
  { name: "Hernan Perez", number: 14 },

  { name: "Luis Lara", number: 18 },
  { name: "Cooper Pratt", number: 12 },
  { name: "Bob Uecker", number: 9 }, // honorary broadcaster number, not a playing number
  { name: "Omar Narvaez", number: 22 },
  { name: "Orlando Arcia", number: 3 },
  { name: "Lorenzo Cain", number: 6 },
  { name: "Corey Knebel", number: 46 },
  { name: "Francisco Rodriguez", number: 57 },
  { name: "Jeremy Jeffress", number: 32 },
  { name: "Casey McGehee", number: 14 },
  { name: "Jason Kendall", number: 18 },
  { name: "Trevor Hoffman", number: 51 },
  { name: "Ted Simmons", number: 23 },
  { name: "Jim Gantner", number: 17 },
  { name: "Gorman Thomas", number: 20 },
  { name: "Don Money", number: 7 },
];
